<a href="https://colab.research.google.com/github/christos8566/freecodecamp_data_analysis.res/blob/main/numpy_intro_lesson/numpy_lesson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Hands on!

 import the libraries

In [3]:
import sys
import numpy as np


# Basic numpy arrays

In [4]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [5]:
a = np.array([1, 2, 3, 4])

In [6]:
b = np.array([0, .5, 1., 1.5, 2.])

In [7]:
# give me this result:  (1, 2)
a[0], a[1]

(1, 2)

In [8]:
# give me this result:  array([1, 2, 3, 4])
a[:]

array([1, 2, 3, 4])

In [9]:
# give me this result:  array([2, 3])
a[1:3]

array([2, 3])

In [10]:
# give me this result:  array([2, 3])
a[1:-1]

array([2, 3])

In [11]:
# give me this result:  array([1, 3])
a[::2]

array([1, 3])

In [12]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [13]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [14]:
# give me this result:  (0.0, 1.0, 2.0)
b[::2]

array([0., 1., 2.])

In [15]:
# give me this result:  array([0., 1., 2.])
b[[0, 2, -1]]

array([0., 1., 2.])

# Arrays Types


In [16]:
a

array([1, 2, 3, 4])

In [17]:
# give me the type of data in the array a
a.dtype

dtype('int64')

In [18]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [19]:
# give me the type of data in the array b
b.dtype

dtype('float64')

In [20]:
# convert the type of data to float64
np.array([1, 2, 3, 4], dtype = float)

array([1., 2., 3., 4.])

In [21]:
# convert the type of array to smaller integer bite
np.array([1, 2, 3, 4], dtype = 'int8')

array([1, 2, 3, 4], dtype=int8)

In [22]:
c = np.array(['a', 'b', 'c'])
c.dtype

dtype('<U1')

In [23]:
d = np.array([{'a' : 6}, sys])

In [24]:
d.dtype

dtype('O')

# Dimensions and shapes

In [25]:
# declare a new array name A
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [26]:
# recognition the numpers of columns and rows at the veriable A, with the shape function
A.shape

(2, 3)

In [27]:
# recognition the numpers of dimensions at the variable A with the ndim function
A.ndim

2

In [28]:
# recognition the total numper of all the rows at the variable A with the function of size
A.size

6

In [29]:
# declare a new array variable name B with three dimension of data
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1],
    ]
])

In [30]:
# recognition the numpers of columns and rows at the variable B with the function of shape
B.shape

(2, 2, 3)

In [31]:
# recognition the numpers of dimensions at the variable B with the function of ndim
B.ndim

3

In [32]:
# recognition the total numpers of all data in the variable B with the function of size
B.size

12

If the shape is not consistent, it'll just fall back to regular Python object

# Indexing and Slicing of Matrices

In [46]:
# square matrix

A = np.array([
  #  0  1  2
    [1, 2, 3], #0
    [4, 5, 6], #1
    [7, 8, 9], #2
])

In [47]:
# select the secont row of elements
A[1]

array([4, 5, 6])

In [48]:
# selct the first element of the second row
A[1, 0] # for the second row 'A[1]' choose the first column 'A[:,0]

4

In [49]:
# alternative approach same with the list
A[1][0]

4

In [52]:
# select the firtst two rows
A[:2] # is same with A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
# select all elements of the last two columns
A[:, 1:] # is same with A[:,  1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [55]:
# select the elements of the first two rows and the first two collumns
A[:2,:2]

array([[1, 2],
       [4, 5]])

In [57]:
# select the elements of the first two rows and the last two columns
A[:2, 1:]

array([[2, 3],
       [5, 6]])

In [58]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
# replace all elements of the second row with the numper of 10
A[1] = np.array([10, 10, 10])

In [69]:
# replace the elements of third row with the numper of 99
A[2] = 99
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

# Summary statistics


In [70]:
a = np.array([1, 2, 3, 4])

In [71]:
# find the sum of all ellements at the array variable a
a.sum()

10

In [72]:
# find the mean of the ellements at the array variable a
a.mean()

2.5

In [73]:
# find the standart deviation of the elemants at the array variable a
a.std()

1.118033988749895

In [74]:
# find the variance at the array variable a
a.var()

1.25

In [75]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [76]:
A.sum()

45

In [77]:
A.mean()

5.0

In [78]:
A.std()

2.581988897471611

In [79]:
A.var()

6.666666666666667

In [81]:
A.sum(axis = 0) # axis = 0 is the axis of columns (vertical)
# in this case it returns an array with the sum of all columns

array([12, 15, 18])

In [ ]:
A.sum(axis = 1) # axis = 1 is the axis of rows (vertical)
# in this case it returns an array with the sum of all rows

In [82]:
A.mean(axis = 0)

array([4., 5., 6.])

In [83]:
A.mean(axis = 1)

array([2., 5., 8.])

In [84]:
A.std(axis = 0)

array([2.44948974, 2.44948974, 2.44948974])

In [85]:
A.std(axis = 1)

array([0.81649658, 0.81649658, 0.81649658])

In [86]:
A.var(axis = 0)

array([6., 6., 6.])

In [87]:
A.var(axis = 1)

array([0.66666667, 0.66666667, 0.66666667])