# Hands on!

 import the libraries

In [ ]:
import sys
import numpy as np


# Basic numpy arrays

In [ ]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
b = np.array([0, .5, 1., 1.5, 2.])

In [ ]:
# give me this result:  (1, 2)
a[0], a[1]

(1, 2)

In [ ]:
# give me this result:  array([1, 2, 3, 4])
a[:]

array([1, 2, 3, 4])

In [ ]:
# give me this result:  array([2, 3])
a[1:3]

array([2, 3])

In [ ]:
# give me this result:  array([2, 3])
a[1:-1]

array([2, 3])

In [ ]:
# give me this result:  array([1, 3])
a[::2]

array([1, 3])

In [ ]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [ ]:
# give me this result:  (0.0, 1.0, 2.0)
b[::2]

array([0., 1., 2.])

In [ ]:
# give me this result:  array([0., 1., 2.])
b[[0, 2, -1]]

array([0., 1., 2.])

# Arrays Types


In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
# give me the type of data in the array a
a.dtype

dtype('int64')

In [ ]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
# give me the type of data in the array b
b.dtype

dtype('float64')

In [ ]:
# convert the type of data to float64
np.array([1, 2, 3, 4], dtype = float)

array([1., 2., 3., 4.])

In [ ]:
# convert the type of array to smaller integer bite
np.array([1, 2, 3, 4], dtype = 'int8')

array([1, 2, 3, 4], dtype=int8)

In [ ]:
c = np.array(['a', 'b', 'c'])
c.dtype

dtype('<U1')

In [ ]:
d = np.array([{'a' : 6}, sys])

In [ ]:
d.dtype

dtype('O')

# Dimensions and shapes

In [ ]:
# declare a new array name A
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [ ]:
# recognition the numpers of columns and rows at the veriable A, with the shape function
A.shape

(2, 3)

In [ ]:
# recognition the numpers of dimensions at the variable A with the ndim function
A.ndim

2

In [ ]:
# recognition the total numper of all the rows at the variable A with the function of size
A.size

6

In [ ]:
# declare a new array variable name B with three dimension of data
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1],
    ]
])

In [ ]:
# recognition the numpers of columns and rows at the variable B with the function of shape
B.shape

(2, 2, 3)

In [ ]:
# recognition the numpers of dimensions at the variable B with the function of ndim
B.ndim

3

In [ ]:
# recognition the total numpers of all data in the variable B with the function of size
B.size

12

If the shape is not consistent, it'll just fall back to regular Python object

# Indexing and Slicing of Matrices

In [ ]:
# square matrix

A = np.array([
  #  0  1  2
    [1, 2, 3], #0
    [4, 5, 6], #1
    [7, 8, 9], #2
])

In [ ]:
# select the secont row of elements
A[1]

array([4, 5, 6])

In [ ]:
# selct the first element of the second row
A[1, 0] # for the second row 'A[1]' choose the first column 'A[:,0]

4

In [ ]:
# alternative approach same with the list
A[1][0]

4

In [ ]:
# select the firtst two rows
A[:2] # is same with A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# select all elements of the last two columns
A[:, 1:] # is same with A[:,  1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
# select the elements of the first two rows and the first two collumns
A[:2,:2]

array([[1, 2],
       [4, 5]])

In [ ]:
# select the elements of the first two rows and the last two columns
A[:2, 1:]

array([[2, 3],
       [5, 6]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# replace all elements of the second row with the numper of 10
A[1] = np.array([10, 10, 10])

In [ ]:
# replace the elements of third row with the numper of 99
A[2] = 99
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

# Summary statistics


In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
# find the sum of all ellements at the array variable a
a.sum()

10

In [ ]:
# find the mean of the ellements at the array variable a
a.mean()

2.5

In [ ]:
# find the standart deviation of the elemants at the array variable a
a.std()

1.118033988749895

In [ ]:
# find the variance at the array variable a
a.var()

1.25

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
A.sum()

45

In [ ]:
A.mean()

5.0

In [ ]:
A.std()

2.581988897471611

In [ ]:
A.var()

6.666666666666667

In [ ]:
A.sum(axis = 0) # axis = 0 is the axis of columns (vertical)
# in this case it returns an array with the sum of all columns (1 + 4 + 8 = 12)

array([12, 15, 18])

In [ ]:
A.sum(axis = 1) # axis = 1 is the axis of rows (vertical)
# in this case it returns an array with the sum of all rows (1 + 2 + 3 = 6)

array([ 6, 15, 24])

In [ ]:
A.mean(axis = 0)

array([4., 5., 6.])

In [ ]:
A.mean(axis = 1)

array([2., 5., 8.])

In [ ]:
A.std(axis = 0)

array([2.44948974, 2.44948974, 2.44948974])

In [ ]:
A.std(axis = 1)

array([0.81649658, 0.81649658, 0.81649658])

In [ ]:
A.var(axis = 0)

array([6., 6., 6.])

In [ ]:
A.var(axis = 1)

array([0.66666667, 0.66666667, 0.66666667])

# Broadcasting and Vectorized operations

In [ ]:
a = np.arange(4) # this returns the range of numbers 4 within the array
a

array([0, 1, 2, 3])

In [ ]:
a + 10 # we add the number 10 to all elements of array

array([10, 11, 12, 13])

In [ ]:
a # the previous result was not kept

array([0, 1, 2, 3])

In [ ]:
a * 10 # we multiply the number 10 to all elements of array

array([ 0, 10, 20, 30])

In [ ]:
a += 100
a # now, we since the operator of equal, the result was stored in variable

array([100, 101, 102, 103])

In [ ]:
l = [0, 1, 2, 3]
[i * 10 for i in l]

[0, 10, 20, 30]

In [ ]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
b = np.array([10, 10, 10, 10])
b

array([10, 10, 10, 10])

In [ ]:
a * b

array([ 0, 10, 20, 30])

# Boolean arrays

In [ ]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
# select the 3 first elements of a
a[:-1]

array([0, 1, 2])

In [ ]:
# and this way
a[[True,True,True,False]]       # returns the elements where they are at the same point as true

array([0, 1, 2])

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
# return the result where they are smaller than 3
a[a<3]

array([0, 1, 2])

In [ ]:
a < 3

array([ True,  True,  True, False])

In [ ]:
a.mean()

1.5

In [ ]:
# return the elements were they are bigger than a.mean()
a[a>a.mean()]

array([2, 3])

In [ ]:
# return the elements were they are not bigger than a.mean()
a[~(a>a.mean())]      # the operator ~ = not

array([0, 1])

In [ ]:
# we would have the same result and in this case:
a[a<a.mean()]

array([0, 1])

In [ ]:
# select the elements 0 or 2
a[(a == 0) | (a == 2)]      # the operator | = or

array([0, 2])

In [ ]:
a[(a >= 2) & (a % 2 == 0)]    # the operator & = end

array([2])

In [ ]:
A = np.random.randint(100, size=[3,3])
A

array([[62, 85, 67],
       [20,  3, 31],
       [86, 66, 34]])

In [ ]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([62, 67,  3, 86, 34])

In [ ]:
A >= 50

array([[ True,  True,  True],
       [False, False, False],
       [ True,  True, False]])

In [ ]:
A[A >= 50]

array([62, 85, 67, 86, 66])

# Linear Algebra


In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [ ]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

# Useful Numpy functions

## Random

In [ ]:
np.random.random(size = 2)

array([0.37468776, 0.30251618])

In [ ]:
np.random.normal(size = 2)

array([-0.01470569,  1.0295158 ])

In [ ]:
np.random.rand(2, 4)

array([[0.63705566, 0.53302999, 0.39484786, 0.40352726],
       [0.15613034, 0.8103702 , 0.37013207, 0.39195205]])

## Arange

In [ ]:
np.arange(10)         # returns all values of range 10 in an array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5, 10)        # returns all values of range between 5 and 10 in an array

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 1, .1)       # returns all values of range 1 where each value is .1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

## Reshape

In [ ]:
np.arange(10).reshape(2, 5)     # modifies the shape of an array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## Linspace

In [ ]:
np.linspace(0, 1, 5)    # this function returns five value between 0 and 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

## Zeros, ones, empty

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.zeros([3, 7])

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros([3, 7], dtype = int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones([2, 3, 3])

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
np.ones([2, 3, 3], dtype = int)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [ ]:
np.empty(4)

array([0., 0., 0., 0.])

In [ ]:
np.empty((3, 3))

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6],
       [0.7, 0.8, 0.9]])

## identity and eye

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(8, 4, k = 2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
"Hello World!"[6]

'W'