# Hands on!

 import the libraries

In [1]:
import sys
import numpy as np


# Basic numpy arrays

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])

In [23]:
b = np.array([0, .5, 1., 1.5, 2.])

In [6]:
# give me this result:  (1, 2)
a[0], a[1]

(1, 2)

In [7]:
# give me this result:  array([1, 2, 3, 4])
a[:]

array([1, 2, 3, 4])

In [8]:
# give me this result:  array([2, 3])
a[1:3]

array([2, 3])

In [11]:
# give me this result:  array([2, 3])
a[1:-1]

array([2, 3])

In [19]:
# give me this result:  array([1, 3])
a[::2]

array([1, 3])

In [24]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [25]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [27]:
# give me this result:  (0.0, 1.0, 2.0)
b[::2]

array([0., 1., 2.])

In [28]:
# give me this result:  array([0., 1., 2.])
b[[0, 2, -1]]

array([0., 1., 2.])

# Arrays Types


In [29]:
a

array([1, 2, 3, 4])

In [32]:
# give me the type of data in the array a
a.dtype

dtype('int64')

In [33]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [34]:
# give me the type of data in the array b
b.dtype

dtype('float64')

In [35]:
# convert the type of data to float64
np.array([1, 2, 3, 4], dtype = float)

array([1., 2., 3., 4.])

In [37]:
# convert the type of array to smaller integer bite
np.array([1, 2, 3, 4], dtype = 'int8')

array([1, 2, 3, 4], dtype=int8)

In [40]:
c = np.array(['a', 'b', 'c'])
c.dtype

dtype('<U1')

In [45]:
d = np.array([{'a' : 6}, sys])

In [46]:
d.dtype

dtype('O')

# Dimensions and shapes

In [47]:
# declare a new array name A
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [48]:
# recognition the numpers of columns and rows at the veriable A, with the shape function
A.shape

(2, 3)

In [49]:
# recognition the numpers of dimensions at the variable A with the ndim function
A.ndim

2

In [50]:
# recognition the total numper of all the rows at the variable A with the function of size
A.size

6

In [51]:
# declare a new array variable name B with three dimension of data
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1],
    ]
])

In [52]:
# recognition the numpers of columns and rows at the variable B with the function of shape
B.shape

(2, 2, 3)

In [53]:
# recognition the numpers of dimensions at the variable B with the function of ndim
B.ndim

3

In [54]:
# recognition the total numpers of all data in the variable B with the function of size
B.size

12

If the shape is not consistent, it'll just fall back to regular Python object

In [58]:
# declare a new array variable with not consistent of its structure
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [59]:
c.dtype

dtype('<U1')