# Numpy Exercise

In [1]:
# import the library of numpy
import numpy as np

# print the numpy version and configuration
print(np.__version__)

1.25.2


## Array Creation

### Create a numpy array of size 10, filled with zeros.

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Create a numpy array with values ranging from 10 to 49

In [3]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### Create a numpy matrix of 2*2 integers, filled with ones.

In [4]:
np.ones([2, 2], dtype = int)

array([[1, 1],
       [1, 1]])

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [5]:
np.ones([3, 2], dtype = float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [8]:
#np.ones([4], dtype = int)
#alternative way to do it with the ones_like()
X = np.arange(4, dtype = int)

np.ones_like(X)

array([1, 1, 1, 1])

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [9]:
np.zeros_like(X)

array([0, 0, 0, 0])

### Create a numpy matrix of 4*4 integers, filled with fives.


In [16]:
np.ones([4, 4], dtype = int) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.


In [23]:
X = np.array([[2, 3], [6, 2]], dtype = int)
np.ones_like(X) * 7

array([[7, 7],
       [7, 7]])

### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [29]:
#np.eye(3)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Create a numpy array, filled with 3 random integer values between 1 and 10

In [33]:
#np.random.random_integers(0, 10, size = 3)
np.random.randint(10, size = 3)

array([9, 0, 8])

### Create a 3*3*3 numpy matrix, filled with random float values.


In [41]:
np.random.randn(3,3,3)
#np.random.rand(3,3,3)

array([[[-4.66987490e-01,  2.71626393e+00,  1.07212529e+00],
        [-1.39244217e+00,  1.07870878e+00, -7.33967464e-01],
        [-1.76503329e-03, -3.31535831e-01,  4.78681547e-02]],

       [[ 1.76257081e-01, -8.70241206e-02, -1.10248373e+00],
        [ 4.53253621e-01,  1.33852696e-01, -1.05678327e-02],
        [-2.03843264e-01, -1.34023525e+00, -1.11216312e+00]],

       [[ 1.77515333e-01, -1.12501387e+00, -1.90789833e+00],
        [ 4.58127522e-01,  4.95257083e-01, -1.01490179e+00],
        [ 3.19641988e-01,  1.67684341e-02,  1.08617890e-01]]])

### Given the X python list convert it to an Y numpy array

In [43]:
X = [1, 2, 3]
print(X, type(X))

[1, 2, 3] <class 'list'>


In [45]:
Y = np.array(X)
print(Y, type(Y))

[1 2 3] <class 'numpy.ndarray'>


### Given the X numpy array, make a copy and store it on Y.

In [47]:
X = np.array([5,2,3], dtype=int)
print(X, id(X))

[5 2 3] 138075622968368


In [48]:
Y = np.copy(X)
print(Y, id(Y))

[5 2 3] 138075622948176
