<a href="https://colab.research.google.com/github/christos8566/freecodecamp_data_analysis.res/blob/main/numpy_intro_lesson/numpy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise

In [2]:
# import the library of numpy
import numpy as np

# print the numpy version and configuration
print(np.__version__)

1.25.2


## Array Creation

### Create a numpy array of size 10, filled with zeros.

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Create a numpy array with values ranging from 10 to 49

In [4]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### Create a numpy matrix of 2*2 integers, filled with ones.

In [5]:
np.ones([2, 2], dtype = int)

array([[1, 1],
       [1, 1]])

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [6]:
np.ones([3, 2], dtype = float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [7]:
#np.ones([4], dtype = int)
#alternative way to do it with the ones_like()
X = np.arange(4, dtype = int)

np.ones_like(X)

array([1, 1, 1, 1])

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [8]:
np.zeros_like(X)

array([0, 0, 0, 0])

### Create a numpy matrix of 4*4 integers, filled with fives.


In [9]:
np.ones([4, 4], dtype = int) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.


In [10]:
X = np.array([[2, 3], [6, 2]], dtype = int)
np.ones_like(X) * 7

array([[7, 7],
       [7, 7]])

### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [11]:
#np.eye(3)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Create a numpy array, filled with 3 random integer values between 1 and 10

In [12]:
#np.random.random_integers(0, 10, size = 3)
np.random.randint(10, size = 3)

array([9, 8, 4])

### Create a 3*3*3 numpy matrix, filled with random float values.


In [13]:
np.random.randn(3,3,3)
#np.random.rand(3,3,3)

array([[[-0.02143122,  1.7918699 , -0.62088011],
        [-0.12360742,  0.62724613,  2.28679457],
        [-1.14041352, -0.73208033,  0.74182057]],

       [[-0.35607797,  1.46812818, -0.49715417],
        [ 0.11585315,  0.58418352,  0.07633074],
        [-0.46457965,  1.90330584, -1.3217291 ]],

       [[-1.87944179,  0.44343336,  0.08212756],
        [-0.7284659 ,  0.09503947, -1.91954025],
        [ 0.77582761, -0.36123817, -0.95427159]]])

### Given the X python list convert it to an Y numpy array

In [14]:
X = [1, 2, 3]
print(X, type(X))

[1, 2, 3] <class 'list'>


In [15]:
Y = np.array(X)
print(Y, type(Y))

[1 2 3] <class 'numpy.ndarray'>


### Given the X numpy array, make a copy and store it on Y.

In [16]:
X = np.array([5,2,3], dtype=int)
print(X, id(X))

[5 2 3] 140235917607248


In [17]:
Y = np.copy(X)
print(Y, id(Y))

[5 2 3] 140235917607632


### Create a numpy array with numbers from 1 to 10


In [18]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Create a numpy array with the odd numbers between 1 to 10





In [19]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

### Create a numpy array with numbers from 1 to 10, in descending order.


In [20]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8


In [21]:
np.arange(9).reshape([3, 3])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Show the memory size of the given Z numpy matrix

In [22]:
Z = np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


## Array indexation

### Given the X numpy array, show it's first element

In [23]:
X = np.array(['A', 'B', 'C', 'D', 'E'])
X[0]

'A'

### Given the X numpy array, show it's last element

In [24]:
X[-1]

'E'

### Given the X numpy array, show it's first three elements


In [25]:
X[0:3]

array(['A', 'B', 'C'], dtype='<U1')

### Given the X numpy array, show all middle elements


In [26]:
X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

### Given the X numpy array, show the elements in reverse position


In [27]:
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

### Given the X numpy array, show the elements in an odd position


In [28]:
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

### Given the X numpy matrix, show the first row elements


In [29]:
X = np.array([
    [1,   2,  3,  4],          #X = np.arange(1, 17).reshape(4, 4)
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])

### Given the X numpy matrix, show the last row elements


In [30]:
X[-1]

array([13, 14, 15, 16])

### Given the X numpy matrix, show the first element on first row

In [31]:
X[0, 0]

1

In [32]:
X[-1, -1]

16

### Given the X numpy matrix, show the middle row elements


In [33]:
X[1:3, 1:3]     #X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

### Given the X numpy matrix, show the first two elements on the first two rows

In [34]:
X[:2, :2]

array([[1, 2],
       [5, 6]])

### Given the X numpy matrix, show the last two elements on the last two rows

In [35]:
X[-2:, -2:]

array([[11, 12],
       [15, 16]])

## Array manipulation

### Convert the given integer numpy array to float


In [39]:
X = [-5, -3, 0, 10, 40]

np.array(X, dtype = float)

array([-5., -3.,  0., 10., 40.])

### Reverse the given numpy array (first element becomes last)


In [43]:
X = [-5, -3, 0, 10, -40]

X[::-1]

[-40, 10, 0, -3, -5]

### Order (sort) the given numpy array


In [51]:
X = [-5, -3, 0, 10, -40]

X.sort()
X

[-40, -5, -3, 0, 10]

### Given the X numpy array, set the fifth element equal to 1

In [52]:
X[-1] = 1
X

[-40, -5, -3, 0, 1]

### Given the X numpy array, change the 50 with a 40


In [53]:
X = np.array([10, 20, 30, 50])

X[-1] = 40
X

array([10, 20, 30, 40])

### Given the X numpy matrix, change the last row with all 1

In [63]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
#X = np.arange(1, 17).reshape(4, 4)

X[-1] = np.ones(4)   # X[-1] = [1, 1, 1, 1]
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

### Given the X numpy matrix, change the last item on the last row with a 0

In [66]:
X = np.arange(1, 17).reshape(4, 4)
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [69]:
X[-1, -1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

### Given the X numpy matrix, add 5 to every element

In [71]:
X = np.arange(1, 17).reshape(4, 4)

X + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

## Boolean arrays (also called masks)

### Given the X numpy array, make a mask showing negative elements

In [75]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

X[X < 0]
#Y = np.copy(X[X < 0])

array([-1, -4, -9])

In [78]:
mask = X < 0
X[mask]           #Y = np.copy(X[mask])

array([-1, -4, -9])

### Given the X numpy array, get numbers higher than 5

In [79]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X > 5
X[mask]              # Y = np.copy(X[mask])

array([ 6, 10])

### Given the X numpy array, get numbers higher than the elements mean


In [80]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > X.mean()
X[mask]

array([ 2,  5,  6, 10])

### Given the X numpy array, get numbers equal to 2 or 10

In [93]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

#X[(X == 2) | (X == 10)]
mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])

## Logic functions

Given the X numpy array, return True if none of its elements is zero

In [101]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
X.all()

False

### Given the X numpy array, return True if any of its elements is zero


In [102]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
X.any()

True

## Summary statistics

### Given the X numpy array, show the sum of its elements


In [103]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
X.sum()

43

### Given the X numpy array, show the mean value of its elements


In [104]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
#np.mean(X)
X.mean()

3.7

### Given the X numpy matrix, show the sum of its columns

In [114]:
#X = np.arange(1, 17).reshape(4, 4)
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X.sum(axis = 0)         # remember: axis=0 columns; axis=1 rows

array([28, 32, 36, 40])

### Given the X numpy matrix, show the mean value of its rows


In [115]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X.mean(axis = 1)

array([ 2.5,  6.5, 10.5, 14.5])

### Given the X numpy array, show the max value of its elements


In [116]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

X.max()

10