<a href="https://colab.research.google.com/github/christos8566/freecodecamp_data_analysis.res/blob/main/numpy_intro_lesson/numpy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise

In [1]:
# import the library of numpy
import numpy as np

# print the numpy version and configuration
print(np.__version__)

1.25.2


## Array Creation

### Create a numpy array of size 10, filled with zeros.

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Create a numpy array with values ranging from 10 to 49

In [3]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### Create a numpy matrix of 2*2 integers, filled with ones.

In [4]:
np.ones([2, 2], dtype = int)

array([[1, 1],
       [1, 1]])

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [5]:
np.ones([3, 2], dtype = float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [6]:
#np.ones([4], dtype = int)
#alternative way to do it with the ones_like()
X = np.arange(4, dtype = int)

np.ones_like(X)

array([1, 1, 1, 1])

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [7]:
np.zeros_like(X)

array([0, 0, 0, 0])

### Create a numpy matrix of 4*4 integers, filled with fives.


In [8]:
np.ones([4, 4], dtype = int) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.


In [9]:
X = np.array([[2, 3], [6, 2]], dtype = int)
np.ones_like(X) * 7

array([[7, 7],
       [7, 7]])

### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [10]:
#np.eye(3)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Create a numpy array, filled with 3 random integer values between 1 and 10

In [11]:
#np.random.random_integers(0, 10, size = 3)
np.random.randint(10, size = 3)

array([2, 9, 9])

### Create a 3*3*3 numpy matrix, filled with random float values.


In [12]:
np.random.randn(3,3,3)
#np.random.rand(3,3,3)

array([[[ 0.89939875,  0.11894438,  1.16719926],
        [-1.53723786, -0.76034249,  1.84128283],
        [-0.21998738,  0.02241474,  0.26024137]],

       [[-0.16141389,  0.63538082,  0.12386787],
        [ 1.04092375,  0.8851715 , -0.58063575],
        [ 1.09291888, -0.18745121, -0.01178365]],

       [[ 0.26480577,  0.04468223, -0.73009751],
        [-0.8511421 ,  0.75409784, -0.40976823],
        [-1.3905993 , -0.78593611,  1.71456914]]])

### Given the X python list convert it to an Y numpy array

In [13]:
X = [1, 2, 3]
print(X, type(X))

[1, 2, 3] <class 'list'>


In [14]:
Y = np.array(X)
print(Y, type(Y))

[1 2 3] <class 'numpy.ndarray'>


### Given the X numpy array, make a copy and store it on Y.

In [15]:
X = np.array([5,2,3], dtype=int)
print(X, id(X))

[5 2 3] 134476304613072


In [16]:
Y = np.copy(X)
print(Y, id(Y))

[5 2 3] 134476304850096


### Create a numpy array with numbers from 1 to 10


In [21]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Create a numpy array with the odd numbers between 1 to 10





In [22]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

### Create a numpy array with numbers from 1 to 10, in descending order.


In [34]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8


In [36]:
np.arange(9).reshape([3, 3])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Show the memory size of the given Z numpy matrix

In [38]:
Z = np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


## Array indexation

### Given the X numpy array, show it's first element

In [39]:
X = np.array(['A', 'B', 'C', 'D', 'E'])
X[0]

'A'

### Given the X numpy array, show it's last element

In [40]:
X[-1]

'E'

### Given the X numpy array, show it's first three elements


In [41]:
X[0:3]

array(['A', 'B', 'C'], dtype='<U1')

### Given the X numpy array, show all middle elements


In [43]:
X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

### Given the X numpy array, show the elements in reverse position


In [47]:
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

### Given the X numpy array, show the elements in an odd position


In [50]:
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

### Given the X numpy matrix, show the first row elements


In [59]:
X = np.array([
    [1,   2,  3,  4],          #X = np.arange(1, 17).reshape(4, 4)
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])

### Given the X numpy matrix, show the last row elements


In [53]:
X[-1]

array([13, 14, 15, 16])

### Given the X numpy matrix, show the first element on first row

In [62]:
X[0, 0]

1

In [63]:
X[-1, -1]

16

### Given the X numpy matrix, show the middle row elements


In [69]:
X[1:3, 1:3]     #X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

### Given the X numpy matrix, show the first two elements on the first two rows

In [71]:
X[:2, :2]

array([[1, 2],
       [5, 6]])

### Given the X numpy matrix, show the last two elements on the last two rows

In [72]:
X[-2:, -2:]

array([[11, 12],
       [15, 16]])

## Array manipulation

### Convert the given integer numpy array to float
