<a href="https://colab.research.google.com/github/christos8566/freecodecamp_data_analysis.res/blob/main/numpy_intro_lesson/numpy_lesson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Hands on!

 import the libraries

In [2]:
import sys
import numpy as np


# Basic numpy arrays

In [3]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [4]:
a = np.array([1, 2, 3, 4])

In [5]:
b = np.array([0, .5, 1., 1.5, 2.])

In [6]:
# give me this result:  (1, 2)
a[0], a[1]

(1, 2)

In [7]:
# give me this result:  array([1, 2, 3, 4])
a[:]

array([1, 2, 3, 4])

In [8]:
# give me this result:  array([2, 3])
a[1:3]

array([2, 3])

In [9]:
# give me this result:  array([2, 3])
a[1:-1]

array([2, 3])

In [10]:
# give me this result:  array([1, 3])
a[::2]

array([1, 3])

In [11]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [12]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [13]:
# give me this result:  (0.0, 1.0, 2.0)
b[::2]

array([0., 1., 2.])

In [14]:
# give me this result:  array([0., 1., 2.])
b[[0, 2, -1]]

array([0., 1., 2.])

# Arrays Types


In [15]:
a

array([1, 2, 3, 4])

In [16]:
# give me the type of data in the array a
a.dtype

dtype('int64')

In [17]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [18]:
# give me the type of data in the array b
b.dtype

dtype('float64')

In [19]:
# convert the type of data to float64
np.array([1, 2, 3, 4], dtype = float)

array([1., 2., 3., 4.])

In [20]:
# convert the type of array to smaller integer bite
np.array([1, 2, 3, 4], dtype = 'int8')

array([1, 2, 3, 4], dtype=int8)

In [21]:
c = np.array(['a', 'b', 'c'])
c.dtype

dtype('<U1')

In [22]:
d = np.array([{'a' : 6}, sys])

In [23]:
d.dtype

dtype('O')

# Dimensions and shapes

In [24]:
# declare a new array name A
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [25]:
# recognition the numpers of columns and rows at the veriable A, with the shape function
A.shape

(2, 3)

In [26]:
# recognition the numpers of dimensions at the variable A with the ndim function
A.ndim

2

In [27]:
# recognition the total numper of all the rows at the variable A with the function of size
A.size

6

In [28]:
# declare a new array variable name B with three dimension of data
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1],
    ]
])

In [29]:
# recognition the numpers of columns and rows at the variable B with the function of shape
B.shape

(2, 2, 3)

In [30]:
# recognition the numpers of dimensions at the variable B with the function of ndim
B.ndim

3

In [31]:
# recognition the total numpers of all data in the variable B with the function of size
B.size

12

If the shape is not consistent, it'll just fall back to regular Python object

# Indexing and Slicing of Matrices

In [32]:
# square matrix

A = np.array([
  #  0  1  2
    [1, 2, 3], #0
    [4, 5, 6], #1
    [7, 8, 9], #2
])

In [33]:
# select the secont row of elements
A[1]

array([4, 5, 6])

In [34]:
# selct the first element of the second row
A[1, 0] # for the second row 'A[1]' choose the first column 'A[:,0]

4

In [35]:
# alternative approach same with the list
A[1][0]

4

In [36]:
# select the firtst two rows
A[:2] # is same with A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
# select all elements of the last two columns
A[:, 1:] # is same with A[:,  1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [38]:
# select the elements of the first two rows and the first two collumns
A[:2,:2]

array([[1, 2],
       [4, 5]])

In [39]:
# select the elements of the first two rows and the last two columns
A[:2, 1:]

array([[2, 3],
       [5, 6]])

In [40]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
# replace all elements of the second row with the numper of 10
A[1] = np.array([10, 10, 10])

In [42]:
# replace the elements of third row with the numper of 99
A[2] = 99
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

# Summary statistics


In [43]:
a = np.array([1, 2, 3, 4])

In [44]:
# find the sum of all ellements at the array variable a
a.sum()

10

In [45]:
# find the mean of the ellements at the array variable a
a.mean()

2.5

In [46]:
# find the standart deviation of the elemants at the array variable a
a.std()

1.118033988749895

In [47]:
# find the variance at the array variable a
a.var()

1.25

In [48]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [49]:
A.sum()

45

In [50]:
A.mean()

5.0

In [51]:
A.std()

2.581988897471611

In [52]:
A.var()

6.666666666666667

In [53]:
A.sum(axis = 0) # axis = 0 is the axis of columns (vertical)
# in this case it returns an array with the sum of all columns (1 + 4 + 8 = 12)

array([12, 15, 18])

In [54]:
A.sum(axis = 1) # axis = 1 is the axis of rows (vertical)
# in this case it returns an array with the sum of all rows (1 + 2 + 3 = 6)

array([ 6, 15, 24])

In [55]:
A.mean(axis = 0)

array([4., 5., 6.])

In [56]:
A.mean(axis = 1)

array([2., 5., 8.])

In [57]:
A.std(axis = 0)

array([2.44948974, 2.44948974, 2.44948974])

In [58]:
A.std(axis = 1)

array([0.81649658, 0.81649658, 0.81649658])

In [59]:
A.var(axis = 0)

array([6., 6., 6.])

In [60]:
A.var(axis = 1)

array([0.66666667, 0.66666667, 0.66666667])

# Broadcasting and Vectorized operations

In [72]:
a = np.arange(4) # this returns the range of numbers 4 within the array
a

array([0, 1, 2, 3])

In [73]:
a + 10 # we add the number 10 to all elements of array

array([10, 11, 12, 13])

In [74]:
a # the previous result was not kept

array([0, 1, 2, 3])

In [75]:
a * 10 # we multiply the number 10 to all elements of array

array([ 0, 10, 20, 30])

In [77]:
a += 100
a # now, we since the operator of equal, the result was stored in variable

array([200, 201, 202, 203])

In [89]:
l = [0, 1, 2, 3]
[i * 10 for i in l]

[0, 10, 20, 30]

In [102]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [103]:
b = np.array([10, 10, 10, 10])
b

array([10, 10, 10, 10])

In [104]:
a * b

array([ 0, 10, 20, 30])

# Boolean arrays

In [106]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [108]:
# select the 3 first elements of a
a[:-1]

array([0, 1, 2])

In [110]:
# and this way
a[[True,True,True,False]]       # returns the elements where they are at the same point as true

array([0, 1, 2])

In [111]:
a

array([0, 1, 2, 3])

In [119]:
# return the result where they are smaller than 3
a[a<3]

array([0, 1, 2])

In [120]:
a < 3

array([ True,  True,  True, False])

In [122]:
a.mean()

1.5

In [121]:
# return the elements were they are bigger than a.mean()
a[a>a.mean()]

array([2, 3])

In [124]:
# return the elements were they are not bigger than a.mean()
a[~(a>a.mean())]      # the operator ~ = not

array([0, 1])

In [126]:
# we would have the same result and in this case:
a[a<a.mean()]

array([0, 1])

In [128]:
# select the elements 0 or 2
a[(a == 0) | (a == 2)]      # the operator | = or

array([0, 2])

In [131]:
a[(a >= 2) & (a % 2 == 0)]    # the operator & = end

array([2])

In [137]:
A = np.random.randint(100, size=[3,3])
A

array([[ 9, 59, 15],
       [18, 36, 30],
       [44, 39, 75]])

In [138]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([ 9, 15, 36, 44, 75])

In [139]:
A >= 50

array([[False,  True, False],
       [False, False, False],
       [False, False,  True]])

In [140]:
A[A >= 50]

array([59, 75])